version: '3'

services:
  react:
    build:
      context: .
      dockerfile: Dockerfile.front
    ports:
      - '3000:3000/tcp'
    command: npm run start
    depends_on:
      - node
    networks:
      - smat

  node:
    build:
      context: .
      dockerfile: Dockerfile.back
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
      - PORT=3333
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    command: npm run prod
    depends_on:
      - postgres
    networks:
      - smat

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-db:/var/lib/postgresql/data
    networks:
      - smat

networks:
  smat: {}

volumes:
  postgres-db:
