version: '3'

services:
  react:
    build:
      context: .
      dockerfile: Dockerfile.front
    ports:
      - '3000:3000/tcp'
    command: npm run start
    depends_on:
      - node
    networks:
      - smat

  node:
    build:
      context: .
      dockerfile: Dockerfile.back
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
      - NODE_PORT=3333
      - DB_HOST=${DATABASE_HOST}
      - DB_USER=${DATABASE_USER}
      - DB_PASS=${DATABASE_PASSWORD}
      - DB_NAME=${DATABASE_NAME}
      - DB_PORT=${DATABASE_PORT}
    command: npm run prod
    depends_on:
      - postgres
    networks:
      - smat

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres-db:/var/lib/postgresql/data
    networks:
      - smat

networks:
  smat: {}

volumes:
  postgres-db:
