FROM node:alpine

WORKDIR /app

COPY ./back/package*.json ./

# Install prod dependencies + typescript
RUN npm install --production
RUN npm install typescript

# Copies source files and tsconfig and transpiles code
COPY ./back .
RUN npm run build

# Copies react build directory
COPY ./front/build ./build

ENV PORT 3333

EXPOSE $PORT

CMD ["npm", "run", "prod"]