version: '3.8'

services:
  react:
    build:
      context: .
      dockerfile: Dockerfile.front
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
    volumes:
      - ./front/src:/react/src
      - ./front/public:/react/public
    depends_on:
      - node
    networks:
      - smat

  node:
    build:
      context: .
      dockerfile: Dockerfile.back
    ports:
      - '3333:3333'
    volumes:
      - ./back/src:/node/src
    environment:
      - PORT=3333
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/smatdb
      - JWT_SECRET=secret_key
    depends_on:
      - postgres
    networks:
      - smat

  postgres:
    image: postgres:13
    restart: always
    # ports:
    #   - '5433:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: smatdb
    volumes:
      - postgres-db:/var/lib/postgresql/data
    networks:
      - smat

networks:
  smat: {}

volumes:
  postgres-db:
