FROM node:16

WORKDIR /node

COPY ./back/package*.json ./

RUN  apt update && apt install ghostscript -y

COPY ./back/replace.bash ./

RUN bash replace.bash

RUN npm install

COPY ./back/ .

CMD ["npm", "run", "dev"]